### ISSUE TITLE
As a user I want a Login and Registration possibility to be able to play the game.

### ISSUE THREAD

**Issue by Cross55** [sopra-fs24-group-35/sopra-fs24-group-35-server#1]
- [ ] sopra-fs24-group-35/sopra-fs24-group-35-server#49
- [ ] sopra-fs24-group-35/sopra-fs24-group-35-client#24
- [ ] sopra-fs24-group-35/sopra-fs24-group-35-server#51
- [ ] sopra-fs24-group-35/sopra-fs24-group-35-server#52
- [ ] sopra-fs24-group-35/sopra-fs24-group-35-server#53

**Comment by Eposs111** [comment]
- [ ] Registration adds a new user to the database.
- [ ] Once logged in you will get redirected to the screen where you can search or create a game lobby.
- [ ] If Login failed you will get an error code and will not be logged in (Error: User already taken)
- [ ] If the username already exists you will get an error code (409) and will be redirected to the login screen.
- [ ] If registration is successful you will automatically be logged in.

**Comment by Eposs111** [comment]
- [ ] Create Screen for Login

**Comment by Eposs111** [comment]
- [ ] Create Screen for Register

**Comment by Eposs111** [comment]
- [ ] Write Login Function that posts [Name, Username] to /login and saves id and token to the localStorage

**Comment by Eposs111** [comment]
- [ ] Write Register Function that posts [Name, Username] to /users and saves id and token to the localStorage

**Comment by Eposs111** [comment]
- [ ] Ensure that Register Logs user in if register is succelful and redirects the player to /game

**Comment by Eposs111** [comment]
- [ ] If Login fails display correct error code and redirect back to login screen

**Comment by Eposs111** [comment]
- [ ] If Register fails display correct error code and redirect back to login screen

**Comment by Eposs111** [comment]
- [ ] Code Post Mapping for /users (Register)

**Comment by Eposs111** [comment]
- [ ] Code PostMapping for /login

**Comment by Eposs111** [comment]
- [ ] Code function loginUser that logs the user in (UserService)

**Comment by Eposs111** [comment]
- [ ] Implement the DTOs required

**Comment by Eposs111** [comment]
- [ ] Implement createUser (userService)

**Comment by Eposs111** [comment]
- [ ] Implement something to check if user exists
